#!/usr/bin/env perl

$version = shift || die "Usage : $0 <version>\n";
$subdir = "spill-${version}";

unless (-d "RELEASES") {
  mkdir "RELEASES", 0755;
}

system ("git tag -s $version");
die "git tag failed" if ($? != 0);
if (-d $subdir) {
  system ("rm -rf $subdir");
}

system ("git archive --format=tar --prefix=RELEASES/${subdir}/ $version | tar xf -");
die "git archive failed" if ($? != 0);

chdir "RELEASES";
$here = qx/pwd/;
chomp $here;
chdir $subdir;

unlink "make_release";
open (OUT, ">version.h");
print OUT "#ifndef PROGRAM_VERSION\n";
print OUT "#define PROGRAM_VERSION \"${version}\"\n";
print OUT "#endif\n";
close OUT;

chdir $here;
system ("tar cvf - $subdir | gzip -9 > ${subdir}.tar.gz");
system ("gpg -b -a -o ${subdir}-tar-gz-asc.txt ${subdir}.tar.gz");


